FROM node:24-alpine

WORKDIR /workspace

RUN npm install --global eslint@10
RUN npm install --global chokidar-cli@3

RUN printf '%s\n' '#!/bin/sh' \
    'if [ "$1" = "watch" ]; then' \
    '    exec chokidar "src/**/*.js" -c "eslint --max-warnings=0 \"src/**/*.js\"" --initial --polling --poll-interval 300' \
    'else' \
    '    exec eslint --max-warnings=0 "src/**/*.js"' \
    'fi' > /entrypoint.sh && chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]