name: Reusable Lint

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install ESLint
        run: npm install --global eslint@9

      - name: Run lint
        run: eslint --max-warnings=0 "src/**/*.js"