name: Package Extension
on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/_lint-action.yaml

  package:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Package and Upload Extension
        id: package
        uses: murar8/gnome-extensions-action@0.1.0
        with:
          source-dir: src
          output-dir: dist
          gettext-domain: revolutionary-clock
          podir: src/po
          extra-source: |
            cacheManager.js
            clockIndicator.js
            datePopup.js
            republicanCalendar.js
            republicanClock.js
            translations.js
            wikiImageManager.js
            locale-ca.js
            locale-en.js
            locale-es.js
            locale-fr.js
            locale
            ui
          # username: ${{ secrets.GNOME_USERNAME }}
          # password: ${{ secrets.GNOME_PASSWORD }}
          # accept-tos: true
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.zip-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
