name: Package Extension
on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/_lint-action.yaml

  package:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Package and publish extension
        id: package
        uses: murar8/gnome-extensions-action@0.1.0
        with:
          source-dir: src
          schema: ../schemas/org.gnome.shell.extensions.revolutionary-clock.gschema.xml
          extra-source: |
            cacheManager.js
            clockIndicator.js
            datePopup.js
            republicanCalendar.js
            republicanClock.js
            translations.js
            wikiImageManager.js
            locale
            ui
          # username: ${{ secrets.GNOME_USERNAME }}
          # password: ${{ secrets.GNOME_PASSWORD }}
          # accept-tos: true
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.zip-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
